# Generated by Django 4.1 on 2022-08-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='channel',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
